### ISSUE TITLE
[Bug]口令红包没有口令直接抢了

### ISSUE THREAD

**Issue by TLBLL** [WJZ-P/LiteLoaderQQNT-Grab-RedBag#10]
抢口令红包的时候，在没发口令的情况下直接抢了，不符合逻辑，容易被封号

**Comment by WJZ-P** [comment]
收到，稍后修复

**Comment by TLBLL** [comment]
> 修好啦，记得给个star ![6c4627c279090fa8db34046bc27c8214](https://private-user-images.githubusercontent.com/110795301/396819072-d1530d28-de1c-4606-8ea9-5edb313b09cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTEwODgsIm5iZiI6MTczNDUxMDc4OCwicGF0aCI6Ii8xMTA3OTUzMDEvMzk2ODE5MDcyLWQxNTMwZDI4LWRlMWMtNDYwNi04ZWE5LTVlZGIzMTNiMDljZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwODMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDY2MmFhZGFiNzNmYmIwY2VkODQ2MWMzMTk2MWRjNmE0ODk0MWNiNTY5NDhhZDg4NDkzNTJlNGFhNTVhZGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V3Adfx---z3Cx9zMsDY4hAENmcxsVRXI7nnNR8NLmqc)

速度好快呀，不过大佬，新版本口令的问题解决了，不过好像多了一个bug，就是1.2.3在设施界面看不到了，我重启也没用，回退到1.2.2是正常的，再切换回1.2.3又不见了，呃
![屏幕截图 2024-12-12 175904](https://github.com/user-attachments/assets/398df0a6-28c7-4dd5-9011-c83a5c07a684)

**Comment by TLBLL** [comment]
也算小bug吧，倒是可以从config.json里面修改设置

**Comment by WJZ-P** [comment]
我知道了，配置文件我忘删了，我的配置目录和你的不一样，所以你的没有，等等哈

**Comment by TLBLL** [comment]
> 修复好啦 ![2b974419a7ba7d972f1e42bdd7ad0a57](https://private-user-images.githubusercontent.com/110795301/396829901-fd1cbf4a-a894-461d-bc93-61e454171770.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTI1MDQsIm5iZiI6MTczNDUxMjIwNCwicGF0aCI6Ii8xMTA3OTUzMDEvMzk2ODI5OTAxLWZkMWNiZjRhLWE4OTQtNDYxZC1iYzkzLTYxZTQ1NDE3MTc3MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwODU2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODExNmQ2YjIyMDJmZWVlNTdiZmM3MzE1ZGYyNjUxZGNlN2YzMGZmZTBjZDE1MjdhZDc3MDM1MGJmYmVjYzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YW1a1fnz68rPVkr0VqK0eW7MGizr57CpNs7vA4kwYDQ)

可以了，大佬牛逼！！！！！

**Comment by WJZ-P** [comment]
![340985bb1e3d9d7fb94605edb12aa77d](https://github.com/user-attachments/assets/3878eac4-5df3-4dbc-a697-4cf9cc2dbe79)
