### ISSUE TITLE
请求增加“不对自己发送红包感谢“功能

### ISSUE THREAD

**Issue by QingXuer** [WJZ-P/LiteLoaderQQNT-Grab-RedBag#11]
原理实现：通过读取payload.msgList[0].senderUin（红包发送者的QQ号）（如果可行的话）对比authData.uin（自己的QQ号）
在发送红包感谢前增加一个if判断

**Comment by WJZ-P** [comment]
可以的，明天更，在打LOL
![b7a3850d03b66abf81095ba66b14196c](https://github.com/user-attachments/assets/a702627d-80f9-4b81-bd9b-93f97dd06446)

**Comment by QingXuer** [comment]
> 可以的，明天更，在打LOL ![b7a3850d03b66abf81095ba66b14196c](https://private-user-images.githubusercontent.com/110795301/398751115-a702627d-80f9-4b81-bd9b-93f97dd06446.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMjU1NTUsIm5iZiI6MTczNTIyNTI1NSwicGF0aCI6Ii8xMTA3OTUzMDEvMzk4NzUxMTE1LWE3MDI2MjdkLTgwZjktNGI4MS1iZDliLTkzZjk3ZGQwNjQ0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxNTAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTM5MGU1MTk5N2Q5MDRlYjAxZmIwYTcyOGYyZTk5YzhlNmE1N2IwZTFjNDU2YWM5NWIxMzg1OTU4N2FkZTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W3nHN8u0LopzMK1_PA5BYYbjV5UE8GEJAPbD73T1W_4)

好快的回复，祝你LOL愉快（

**Comment by WJZ-P** [comment]
输了两把了，再打一把不打睡觉去了
![cee65fa2dfb0facee17b1f06c99c9c4b](https://github.com/user-attachments/assets/79a9cac2-a827-4cab-b32e-7b18bff360a1)

**Comment by QingXuer** [comment]
> 输了两把了，再打一把不打睡觉去了 ![cee65fa2dfb0facee17b1f06c99c9c4b](https://private-user-images.githubusercontent.com/110795301/398751897-79a9cac2-a827-4cab-b32e-7b18bff360a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMjU4NzMsIm5iZiI6MTczNTIyNTU3MywicGF0aCI6Ii8xMTA3OTUzMDEvMzk4NzUxODk3LTc5YTljYWMyLWE4MjctNGNhYi1iMzJlLTdiMThiZmYzNjBhMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxNTA2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2M2ZGIyYjViZWE2Y2IwZmNjN2UyOGIzNDU4Y2IyNmZhNmU3MmVhMjU5OGM0ZWNkOGY1ZWQ2ZmMzMDVlNzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.faAbBUlb4IS1c6vzMRQbuImx9yGYEpAh59rZD2RrERY)

刚刚自己写了程序，请问我可以pr吗（

**Comment by WJZ-P** [comment]
你先提交，看完没问题我就合并

**Comment by WJZ-P** [comment]
这个功能的话就一行，我感觉我自己加也行，明天顺便把另外的issue搞一搞
![ba856cc3237e1e7817754d145d2d079c](https://github.com/user-attachments/assets/e2611109-9484-4b87-a89f-c08b1466c5cc)

**Comment by QingXuer** [comment]
> 这个功能的话就一行，我感觉我自己加也行，明天顺便把另外的issue搞一搞
> ![ba856cc3237e1e7817754d145d2d079c](https://github.com/user-attachments/assets/e2611109-9484-4b87-a89f-c08b1466c5cc)
> 

是的，就几行代码所以我直接自己动手写了一下。
顺便蹭个pr（）

**Comment by WJZ-P** [comment]
好辣，合并了
![340985bb1e3d9d7fb94605edb12aa77d](https://github.com/user-attachments/assets/a7f855fd-3f17-4918-9138-789a3d4b38f1)

**Comment by QingXuer** [comment]
> 好辣，合并了
> ![340985bb1e3d9d7fb94605edb12aa77d](https://github.com/user-attachments/assets/a7f855fd-3f17-4918-9138-789a3d4b38f1)
> 

谢谢喵www
