### ISSUE TITLE
[BUG] 动态开关功能不生效

### ISSUE THREAD

**Issue by jhqwqmc** [WJZ-P/LiteLoaderQQNT-Grab-RedBag#2]
> qq版本: 9.9.16-28971
> ll版本: 1.2.2
> 插件版本: 1.0.0

在设置中关闭后发送红包仍然可以触发自动抢红包

**Comment by WJZ-P** [comment]
收到，有空测试。动态开关失效的话，重启应该是会生效的。暂时先重启看看吧

**Comment by jhqwqmc** [comment]
好的

**Comment by WJZ-P** [comment]
使用最新版试试，更新了

**Comment by jhqwqmc** [comment]
没问题了
![image](https://github.com/user-attachments/assets/00a4ee1d-f863-473e-9573-1a36a6fa057b)
不过可以给这两个配置加个白名单机制吗，黑名单的话群太多了不是很好配置

**Comment by WJZ-P** [comment]
吃我一记曼巴铁肘
![be810401e222ae0b0e27a00d036644d9](https://github.com/user-attachments/assets/42e77e93-0266-4ae0-a85a-1157e340b333)

**Comment by WJZ-P** [comment]
有空改，歇一会
