### ISSUE TITLE
插件冲突

### ISSUE THREAD

**Issue by Nathalie-Annis** [WJZ-P/LiteLoaderQQNT-Grab-RedBag#3]
和轻量工具箱https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/tree/v4
精简侧边栏功能有冲突，如果QQ启动时加载抢红包插件就会使得侧边栏精简失效

**Comment by WJZ-P** [comment]
![4dd66d03980be7196ede91edbdde9fb3](https://github.com/user-attachments/assets/648455dc-a266-4d5d-8865-65614037ae9b)

**Comment by Nathalie-Annis** [comment]
哈哈，搜了搜办法，改qq的css还是可以精简侧边栏的，和咱们插件不冲突~不用麻烦作者修改了，打扰啦！

**Comment by WJZ-P** [comment]
行，我插件没改动过渲染层的东西，排查起来可能麻烦点，觉得好用的话不要吝啬你的star哦！
![fd802d9023d71c60e81fe29ed89cd3ea](https://github.com/user-attachments/assets/c688ac45-1551-474b-8fab-af40ba165093)
