### ISSUE TITLE
群监听功能

### ISSUE THREAD

**Issue by Wexevou** [WJZ-P/LiteLoaderQQNT-Grab-RedBag#4]
群监听功能 是否可监听已屏蔽消息的群？

**Comment by WJZ-P** [comment]
测试了，屏蔽的群是不可以的，收到群助手里面的可以

**Comment by Wexevou** [comment]
好的 感谢

**Comment by Wexevou** [comment]
但如果是接收消息并不提醒是否可以？

**Comment by WJZ-P** [comment]
肯定可以啊，测试过的

**Comment by lasky141414** [comment]
您好，我这边设置消息免打扰 类型为接收消息并不提醒 无法自动抢，是有更新吗

**Comment by WJZ-P** [comment]
> 您好，我这边设置消息免打扰 类型为接收消息并不提醒 无法自动抢，是有更新吗

这个应该是bug哦，但是我测试的时候是没有问题的，就连收到群助手里面的都可以，不知道你这个是什么情况，是持续出现吗？重启QQ之后会不会正常？

**Comment by lasky141414** [comment]
> > 您好，我这边设置消息免打扰 类型为接收消息并不提醒 无法自动抢，是有更新吗
> 
> 这个应该是bug哦，但是我测试的时候是没有问题的，就连收到群助手里面的都可以，不知道你这个是什么情况，是持续出现吗？重启QQ之后会不会正常？

我目前测试好像又可以了，不知是何原因，有机会复现之后我再询问您，麻烦了

**Comment by WJZ-P** [comment]
> > > 您好，我这边设置消息免打扰 类型为接收消息并不提醒 无法自动抢，是有更新吗
> > 
> > 
> > 这个应该是bug哦，但是我测试的时候是没有问题的，就连收到群助手里面的都可以，不知道你这个是什么情况，是持续出现吗？重启QQ之后会不会正常？
> 
> 我目前测试好像又可以了，不知是何原因，有机会复现之后我再询问您，麻烦了
![676b0baa207d32b64b2998baf75d041c](https://github.com/user-attachments/assets/7052d80c-55ff-4dd8-8c1a-ef69e3a56c09)

**Comment by Wexevou** [comment]
疑似新版QQ无法识别红包自动抢，未屏蔽状态小号发送红包至群里不会自动抢

**Comment by WJZ-P** [comment]
新建.bat文件，输入
~~~
@echo off
chcp 65001
TITLE NTQQ
"E:\NTQQ\QQ.exe" --enable-logging
~~~

QQ路径修改为你自己的，然后启动它，看看别人发红包的时候控制台有没有提示相应的红包消息

**Comment by Wexevou** [comment]
有消息，也成功抢到了，看样子是最近反馈的那个问题，NT本身的问题无法识别其它支付方式
