### ISSUE TITLE
希望增加黑/白名单功能、随机回复语功能

### ISSUE THREAD

**Issue by singularity2000** [WJZ-P/LiteLoaderQQNT-Grab-RedBag#5]
黑名单填写群号，名单内的群不抢；
白名单填写群号，只抢名单内的群。
黑/白名单只能开启其中之一

随机回复语可让用户自行添加，一行一句，自动回复时任选其中一句。
（还可以加一个随机回复延迟，以领到红包作为计时起点）

很赞的插件！但愿能存活到2025春节

**Comment by WJZ-P** [comment]
行，有空做

**Comment by Wexevou** [comment]
刚好我也想来反馈随机回复词功能

**Comment by WJZ-P** [comment]
过一会发release，选择的是跟群聊一样逗号隔开

**Comment by WJZ-P** [comment]
会的，今天不早了，明天发吧，还没测试完
