### ISSUE TITLE
通知重复播报

### ISSUE THREAD

**Issue by Mtxgeek** [WJZ-P/LiteLoaderQQNT-Grab-RedBag#8]
![bug](https://github.com/user-attachments/assets/5c37257f-6ecf-4e10-896f-0c9aa3c062af)
抢失败或者成功 会重复播报

**Comment by WJZ-P** [comment]
奇葩，没有遇到过，请问在什么情况下会出现这个情况？

**Comment by Mtxgeek** [comment]
随机复现  但是昨晚重复2次变成了重复4次 搞得我以为抢了四个包

**Comment by WJZ-P** [comment]
我有空排查下，你还安装了什么其他插件吗？

**Comment by Mtxgeek** [comment]
![QQ20241118-085252](https://github.com/user-attachments/assets/2d38268c-6140-4023-ac90-0d000d5d4423)

**Comment by WJZ-P** [comment]
修复了，下新版试试

**Comment by Mtxgeek** [comment]
ok 没问题了
