### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by WilliamZeng857** [WJZ-P/LiteLoaderQQNT-Grab-RedBag#9]
昨天试的时候还好好的
今天发现就突然就
[QQ红包]请使用新版手机QQ查收红包
是因为被 QQ 检测到了，所以说电脑端不让用了吗
有没有办法恢复？

**Comment by WJZ-P** [comment]
不是，目前大可不必有这个过滤，是因为支付方式不是QQ钱包造成的。NTQQ无法解析使用其他支付方式支付的钱包，是NTQQ自身的问题
![e369ec1f6b8518fa43b15b7ea6b3b7d5](https://github.com/user-attachments/assets/cf3b1949-3d15-422d-a3eb-c37abe19d9bb)

**Comment by WilliamZeng857** [comment]
我去,回复好快
我听他说是:"我是直接让微信红包发在QQ里的"
这种就识别不了吗

**Comment by WJZ-P** [comment]
是的。这种不行哦。必须是QQ红包里面使用QQ支付才可以。NTQQ兼容没做好，其实实际上只有一个字段的差别，完全不影响收的，但是客户端这边没做好处理，直接不支持了

**Comment by WilliamZeng857** [comment]
好嘛
谢谢你的解答
(回复好快)
我都完全不懂这些
就只是一个工具的使用者

**Comment by WJZ-P** [comment]
行

**Comment by WJZ-P** [comment]
我还做了其他的一些插件，有兴趣可以看看，喜欢帮忙star一下
![72ef04bf5d527e72f1ef069db23c02e9](https://github.com/user-attachments/assets/62e33735-942e-4e4f-9e58-37a6e0f5fe56)

**Comment by WilliamZeng857** [comment]
好(那个+1也挺好用的，就是有时候有点不显示)

**Comment by WJZ-P** [comment]
> 好(那个+1也挺好用的，就是有时候有点不显示)

有点bug
